models/Ideas.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "ideas".
 *
 * @property integer $id
 * @property integer $project_id
 * @property string $ideas_description
 * @property integer $stormer_id
 * @property integer $created_at
 * @property integer $updated_at
 */
class Ideas extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ideas';
    }

    public function scenarios()
    {
        return [
            'organize' => ['organize','created_at','updated_at'],
            'flagging' => ['flagging','created_at','updated_at'],
            'divergent' => ['project_id', 'ideas_description','stormer_id','created_at','updated_at'],
            'wholepicture' => ['project_id','parent_id', 'ideas_description','stormer_id','created_at','updated_at'],
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['project_id', 'ideas_description', 'stormer_id'], 'required'],
            [['project_id', 'stormer_id','created_at','updated_at'], 'integer'],
            [['ideas_description'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'project_id' => 'Project ID',
            'ideas_description' => 'Ideas Description',
            'stormer_id' => 'Stormer ID',
        ];
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'stormer_id']);
    }
    public function getOrganize()
    {
        return $this->hasOne(Organizeidea::className(), ['idea_id' => 'id']);
    }

    public function getOrganization()
    {
        return $this->hasOne(Organizeidea::className(), ['idea_id' => 'id']);
    }
    public function getProject()
    {
        return $this->hasOne(Projects::className(), ['id' => 'project_id']);
    }

    public function Stormerv($project_id, $user_id){
        $stormers = Projectstormer::find()->where(['project_id'=>$project_id, 'confirmation'=>1])->orderBy(['updated_at'=>SORT_ASC])->all();
        $mas_stormer=null;
        if($stormers){
            $k=1;
            foreach($stormers as $stormer){
                $mas_stormer[$stormer->stormer_id]=$k;
                $k++;
            }
            return 'Stormer'.$mas_stormer[$user_id];
        }else{
            return 'Stormer';
        }

    }
    public function beforeSave($insert){
        if ($this->isNewRecord){


        }
        return parent::beforeSave($insert);
    }
}

views/admin/_form_create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\assets\ProjectAsset;
ProjectAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-form">

	<?php $form = ActiveForm::begin(); ?>

	<div class="row">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-6">
					<label>Project Title
						<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
							<p>
								Reduce barriers in your project as much as you can by removing unnecessary industry lingo, and breaking down the problem to its simplest determining factor.
							</p>
							<p>
								Eg. Rather than: “Methods of Catching Institutional Memory and Knowledge”
							</p>
							<p>
								Instead: “Ways to share and record the knowledge of employees”
							</p>">i</a>
					</label>
					<?= $form->field($model, 'title')->textInput(['maxlength' => true, 'placeholder'=>'An Amazing New Toothbrush'])->label(false); ?>
					
					<label>Project Description
							<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
								<p>
									Describe the situation you want your team to focus on as clearly as you can. To get really creative answers, try to open your project to people with different fields of knowledge.
								</p>
								Consider:
									<ol>
										<li>
											Can you remove any industry or knowledge-specific lingo?<br>
										</li>
										<li>
											Are the instructions clear? If you asked someone with no prior knowledge to the project or situation to read this description, would they understand?<br>
										</li>
										<li>
											Are there any other limiting factors you can remove? The more limits you place on the project, the more limited your range of answers will be. Knowledge can sometimes be removed for the creative-thinking stage, and then applied again for the application stage.<br>
										</li>
									</ol>
							" >i</a>
					</label>
					<?= $form->field($model, 'description')->textarea(['rows' => 6, 'placeholder' => 'Can we think of new ways to brush our teeth...'])->label(false); ?>
	
					<label>Project Goals
							<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
								<p>
									What goals do you want your team to accomplish during the innovation process? Remember not to communicate your evaluation criteria here. Stormers shouldn’t know how you’ll be judging their answers, as that could greatly influence their ability to exceed expectations with really creative ideas.
								</p>
								<p>
									Eg. Rather than: “Solutions should be web-based and easy to implement”
								</p>
									Instead: “Consider how to apply the ideas and the channels that will be used”
								</p>" >i</a>
					</label>
					<?= $form->field($model, 'goals')->textarea(['rows' => 6, 'placeholder' => 'Unlike anything currently available!'])->label(false) ?>
	
				</div>
				<div class="col-md-6">
					<label>Evaluation Benchmark
							<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
								<p>
									What do you consider to be a successful solution? This is not communicated to the stormers, but back to yourself during the organization stage, at the end of your project.
								</p>
								<p>
									Your evaluation benchmark is important to consider before the project begins, as that allows you to identify which solutions are in “the box”, and which are not.
								</p>" >i</a>
					</label>
					<?= $form->field($model, 'evaluation_benchmark')->textarea(['rows' => 6, 'placeholder' => 'Cost effective and improves cleaning function...'])->label(false) ?>
	
					<div id="datetimepicker1" class="date">
						<label>Timeline for Completion
							<a class="infoButtonShow">i</a>
							<div class="infoBlockShow">
								<div class="arrow"></div>
								<p>Take as much time as you need. The minimum project time is 5 days. If this is too long for you, please let us know. We are currently measuring both demand for, as well as practical applications of shorter innovation challenges to ensure quality is not compromised.</p>
								<p>If you think the deadline is too far in advance, <a class="not_corect_timeline">click here</a>.</p>
							</div>
						</label>
						<!-- <input data-format="yyyy-MM-dd hh:mm:ss" type="text" class='form-control from'></input> -->
						<?= $form->field($model, 'end_date')->textInput(['class' => "date add-on form-control","data-format"=> "yyyy-MM-dd hh:mm:ss"])->label(false); ?>
					</div>

					<div class="form-group">
						<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-create create' : 'btn btn-create']) ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php ActiveForm::end(); ?>

</div>

views/admin/_form_target.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use app\assets\ProjectAsset;
ProjectAsset::register($this);
/* @var $this yii\web\View */
/* @var $model app\models\Projects */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="projects-form">

	<?php $form = ActiveForm::begin(); ?>

		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-6">
					<label>Project Title
						<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
							<p>
								Reduce barriers in your project as much as you can by removing unnecessary industry lingo, and breaking down the problem to its simplest determining factor.
							</p>
							<p>
								Eg. Rather than: “Methods of Catching Institutional Memory and Knowledge”
							</p>
							<p>
								Instead: “Ways to share and record the knowledge of employees”
							</p>">i</a>
					</label>
					<?= $form->field($model, 'title')->textInput(['maxlength' => true, 'placeholder'=>'An Amazing New Toothbrush'])->label(false); ?>
		
					<label>Project Description
						<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
							<p>
								Describe the situation you want your team to focus on as clearly as you can. To get really creative answers, try to open your project to people with different fields of knowledge.
							</p>
							Consider:
								<ol>
									<li>
										Can you remove any industry or knowledge-specific lingo?<br>
									</li>
									<li>
										Are the instructions clear? If you asked someone with no prior knowledge to the project or situation to read this description, would they understand?<br>
									</li>
									<li>
										Are there any other limiting factors you can remove? The more limits you place on the project, the more limited your range of answers will be. Knowledge can sometimes be removed for the creative-thinking stage, and then applied again for the application stage.<br>
									</li>
								</ol>
							" >i</a>
					</label>
					<?= $form->field($model, 'description')->textarea(['rows' => 6, 'placeholder' => 'Can we think of new ways to brush our teeth...'])->label(false); ?>
		
					<label>Project Goals
						<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
							<p>
									What goals do you want your team to accomplish during the innovation process? Remember not to communicate your evaluation criteria here. Stormers shouldn’t know how you’ll be judging their answers, as that could greatly influence their ability to exceed expectations with really creative ideas.
								</p>
								<p>
									Eg. Rather than: “Solutions should be web-based and easy to implement”
								</p>
									Instead: “Consider how to apply the ideas and the channels that will be used”
								</p>" >i</a>
					</label>
					<?= $form->field($model, 'goals')->textarea(['rows' => 6, 'placeholder' => 'Unlike anything currently available!'])->label(false); ?>
				</div>
				<div class="col-md-6">
					<label>Evaluation Benchmark
						<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
							<p>
									What do you consider to be a successful solution? This is not communicated to the stormers, but back to yourself during the organization stage, at the end of your project.
								</p>
								<p>
									Your evaluation benchmark is important to consider before the project begins, as that allows you to identify which solutions are in “the box”, and which are not.
								</p>" >i</a>
					</label>
					<?= $form->field($model, 'evaluation_benchmark')->textarea(['rows' => 6, 'placeholder' => 'Cost effective and improves cleaning function...'])->label(false); ?>

					<div id="datetimepicker1" class="date">
						<label>Timeline for Completion
							<a class="infoButtonShow">i</a>
							<div class="infoBlockShow">
								<div class="arrow"></div>
								<p>Take as much time as you need. The minimum project time is 5 days. If this is too long for you, please let us know. We are currently measuring both demand for, as well as practical applications of shorter innovation challenges to ensure quality is not compromised.</p>
								<p>If you think the deadline is too far in advance, <a class="not_corect_timeline">click here</a>.</p>
							</div>
						</label>
					<!-- <input data-format="yyyy-MM-dd hh:mm:ss" type="text" class='form-control from'></input> -->
					<?= $form->field($model, 'end_date')->textInput(['class' => "date add-on  form-control","data-format"=> "yyyy-MM-dd hh:mm:ss"])->label(false) ?>
				</div>
				<div class="form-group">
					<?= $form->field($model, 'category')->dropDownList($categories) ?>
					<label>Define Your Own Innovation Category:
							<a class="titleDesignProject" data-placement="bottom" data-toggle="tooltip" title="
							<p>
								The project category tells the system what kind of innovation process to use. You can also control that manually on the next page. Selecting a category will also show you possible scope for that group.
							</p>
							<p>
								If you don’t feel any of these match the problem you’re presenting, then write your own. We’ll help you set the system on the next page.
							</p>" >i</a>
						</label>
						<?= $form->field($model, 'tmpCategory')->textInput(['placeholder'=>'Mechanical Engineering'])->label(false); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>

		<div class="col-sm-12 bottom-blok">
			<div class="row">
				<div class="col-md-push-6 col-md-6">
					<div class="col-sm-8 col-sm-offset-2 text-center">
						<img class="category_icon" src="../../../image/project/target/employee_engagement.png" style="width:100%;">
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="col-md-pull-6 col-md-6">
					<div class="modal-button-wrap">
						Try to consider how your project will influence other factors.
						You can always break down a larger mission into several smaller ones. 
						<a href="#" data-toggle="modal" data-target="#myModal">Click here</a> for more information on pricing on our packages.
					</div>
					<div class="form-group text-center">
						<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-create' : 'btn btn-crate']) ?>
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<?=$form->field($model,'size_team')->hiddenInput(['id'=>'size_team'])->label(false)?>
		<?=$form->field($model,'count_idea')->hiddenInput(['id'=>'count_idea'])->label(false)?>

	<?php ActiveForm::end(); ?>

</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Not Just For Big Players</h4>
				<hr>
			</div>
			<div class="modal-body">
				<div class="customerInfoTextBlock">
					<div class="col-md-offset-2 col-md-8">
						<h3 class="title-team">Inexpensive and flexible pricing system</h3>
						<div class="range-title">
							Select the size of your team
						</div>
						<div class="range-wrap">
							<div id="slider_team_size"></div>
						</div>
						<div class="range-title">
							Select the scope of your project (ideas to be generated per stormer)<a style="cursor:pointer;" class="titleDesign" data-placement="bottom" data-toggle="tooltip" title="<h4>Ideas VS Solutions</h4><p style='font-size:14px;'>Our system employs both the divergent creative stage of the ideation process, as well as the practical convergent stage. Therefore with a little help, every idea is a potential solution.</p>" >i</a>
						</div>
						<div class="range-wrap">
							<div id="slider_scope_project"></div>
						</div>
						<div class="price-wrap">
							<h4 class="price-title">Price($)</h4>
							<span class="sliderPrice">0</h4>
						</div>
					</div>
					<div class="clearfix"></div>
					<div class="btn-wrap">
						<div class="col-sm-12">
							<div class="row">
								<div class="col-sm-12 col-md-4">
									<h6 class="titleDesign"  data-toggle="tooltip" title="<h4>Size Vs Scope </h4><p style='font-size:14px;'>Research is quite inconclusive whether a larger team producing fewer ideas will out, equal or under perform a smaller team with more ideas. For best results, we recommend a team large enough to apply a wide range of knowledge, and a scope large enough to provide a wide range of answers. </p>" >Why those numbers?</h6>
									<a class="btn btn-help our_recomendation_customer">Our Recommendation</a>
								</div>
								<div class="col-sm-12 col-md-4">
									<h6>Click here to contact us</h6>
									<?php echo HTML::a(\Yii::t('app', 'Not Sure?'), '/contact', ['class' => 'btn btn-help', 'style' => 'btn btn-help']); ?>
								</div>
								<div class="col-sm-12 col-md-4">
									<h6>Send this quote via email</h6>

									<?php $form = ActiveForm::begin(['id' => 'contact-form', 'action' => '/site/emailquote', 'method' => 'GET']); ?>
									<input type='hidden' name='scope_project'>
									<input type='hidden' name='team_size'>
									<input type='hidden' name='count_price'>
									<?= Html::submitButton('Email Quote', ['class' => 'btn btn-help', 'name' => 'contact-button']) ?>
									<?php ActiveForm::end(); ?>

								</div>
							</div>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-save" data-dismiss="modal">Save</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

views/admin/discountproject.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\assets\AdminAsset;
use yii\bootstrap\ActiveForm;
AdminAsset::register($this);
/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="dashboard-container">

    <div class="container">
        <div id="cssmenu">
            <?php echo $this->render('menu'); ?>
        </div>
        <div class="sub-nav hidden-sm hidden-xs">
            <ul>
                <li>
                    <?php echo HTML::a(\Yii::t('app', '<i class="fa fa-home"></i> Home </a><a> <i class="fa fa-arrow-right"> </i> </a><a style="font-size:15px;padding:0px;">Discount Project'), '/admin/discountproject',['class'=>'AdminHomePageLink']); ?>
                </li>
            </ul>
        </div>

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper-lg">
            <div class="projects-index">
                <p>
                    <?= Html::a('Create Discount Project', ['discountproject/create'], ['class' => 'btn btn-success']) ?>
                </p>
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],

//                        'id',
                        'count',
                        'discount',

                        ['class' => 'yii\grid\ActionColumn',
                            'template'=>'{update}{delete}',
                            'buttons' => [
                                'update' => function ($url, $model, $key) {
                                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>','/discountproject/update?id='.$model->id);
                                },
                                'delete' => function ($url, $model, $key) {
                                    return Html::a('<span class="glyphicon glyphicon-trash"></span>','/discountproject/delete?id='.$model->id);
                                },
                            ],
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>
</div>

views/admin/feedback.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\assets\AdminAsset;
use yii\bootstrap\ActiveForm;
AdminAsset::register($this);
/* @var $this yii\web\View */
/* @var $searchModel app\models\ProjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $feedback app\models\Feedback */
?>
<div class="dashboard-container">

    <div class="container">
        <div id="cssmenu">
            <?php echo $this->render('menu'); ?>
        </div>
        <div class="sub-nav hidden-sm hidden-xs">
            <ul>
                <li>
                    <?php echo HTML::a(\Yii::t('app', '<i class="fa fa-home"></i> Home </a><a> <i class="fa fa-arrow-right"> </i> </a><a style="font-size:15px;padding:0px;">Feedback'), '/admin/feedback',['class'=>'AdminHomePageLink']); ?>
                </li>
            </ul>
        </div>

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper-lg">
            <div class="projects-index">

                <h1><?= Html::encode($this->title) ?></h1>
                <?php if($message){?>
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Update Got!</strong> <?=$message_send?>
                    </div>
                <?php }?>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">


                    <?php foreach($model as $feedback){ ?>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwo">
                                <h4 class="panel-title">
                                    <?php if ($feedback->question <> 2){?>
                                        <button style="margin-top: -10px" class="btn btn-primary pull-right" onclick="update_modal(<?=$feedback->id?>,'<?=$feedback->project['title']?>')"><span class="glyphicon glyphicon-pencil"></span></button>
                                    <?php }?>
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo<?=$feedback->id?>" aria-expanded="false" aria-controls="collapseTwo">
                                        Project "<?=$feedback->project['title']?>",  Date: "<?= Yii::$app->formatter->asDatetime($feedback->created_at)?>", User "<?=$feedback->user['username']?>", Show for site:<?=($feedback->show_status)?'Yes':'No'?>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwo<?=$feedback->id?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="panel-body">
                                    <div class="col-sm-12">

                                        <label style="text-align: left" class="control-label">Please rate how you found the quality of ideas and solutions in this project (from 1-5 stars)</label>
                                        <input class="ratingOne" type="number" value="<?=$feedback->ranting_1?>" />

                                        <label style="text-align: left" class="control-label">Please rate how you found the quality of user experience (from 1-5 stars)</label>
                                        <input class="ratingTwo" type="number" value="<?=$feedback->ranting_2?>"/>

                                        <label style="text-align: left" class="control-label">How likely are you to recommend us to another business, from a score of 1-10 (1 being very unlikely, 10 being very likely)</label>
                                        <input class="ratingThree" type="number" value="<?=$feedback->ranting_3?>" />


                                            <label>Tell us about your experience so far. We’d love to know! </label>
                                           <p> <?=$feedback->about_experience?></p>

                                            <label>Would you object to this review being used as a testimonial for our site?</label>
                                            <p><?php
                                            $mas[1]='yes, I would';
                                            $mas[2]='no, I wouldn’t';
                                                $mas[3]='';
                                            echo $mas[$feedback->question];
                                            ?></p>

                                    </div>
                                </div>
                            </div>
                        </div>

                    <?php }?>
                </div>

                <div class="col-sm-12">
                    <?php echo \yii\widgets\LinkPager::widget([
                        'pagination' => $pages,
                    ]); ?>
                </div>

            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Show feedback for site</h4>
            </div>
            <?php $form = ActiveForm::begin()?>
            <div class="modal-body">
                <input type="hidden" name="up_project_id" id="up_project_id" value="">
                <div class="form-group">
                    <label for="message-text" class="control-label">Show:</label>
                    <select name="up_project_active">
                        <option value="1">Yes</option>
                        <option value="0">No</option>
                    </select>
                </div>
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Update</button>
            </div><?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<script>
    function update_modal(project_id,title){
        $('#up_project_id').val(project_id);
        $('#up_project_title').val(title);
        $('#myModal').modal('show');
    }
</script>

views/admin/project.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\assets\AdminAsset;
use yii\widgets\LinkPager;
use dosamigos\tinymce\TinyMce;
use yii\bootstrap\Alert;

AdminAsset::register($this);
?>
<div class="dashboard-container">

      <div class="container">
        <div id="cssmenu">
            <?php echo $this->render('menu'); ?>
        </div>
        <div class="sub-nav hidden-sm hidden-xs">
          <ul>
            <li>
                <?php echo HTML::a(\Yii::t('app', '<i class="fa fa-home"></i> Home </a><a> <i class="fa fa-arrow-right"> </i> </a><a style="font-size:15px;padding:0px;">Project'), '#',['class'=>'AdminHomePageLink']); ?>
            </li>
          </ul>
        </div>

        <!-- Dashboard Wrapper Start -->
        <div class="dashboard-wrapper-lg">
          <?php
                if(Yii::$app->session->hasFlash('news_added')):
                    echo Alert::widget([
                        'options' => [
                            'class' => 'alert-info',
                        ],
                        'body' => 'News added',
                    ]);
                endif; 
                if(Yii::$app->session->hasFlash('news_notadded')):
                    echo Alert::widget([
                        'options' => [
                            'class' => 'alert-error',
                        ],
                        'body' => 'News not added',
                    ]);
                endif; 
            ?>
          <!-- Row Start -->
          <div class="row wrap" >
            <div class="row wrap" >
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 20px">
                    <div class="widget">
                        <div class="widget-header">
                          <div class="title" style="height:40px;">
                            <i class="fa fa-arrow-down" data-action="show"> </i> Project
                            <span class="mini-title displayNone">
                                
                            </span>
                          </div>
                        </div>
                        <div class=" widget-body">
                            <div class="col-sm-12">
                                <table class="table">
                                    <tr>
                                        <td colspan="2"><b>Title</b></td>
                                        <td colspan="2"><?= $modelProject->title; ?></td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"><b>Description</b></td>
                                        <td colspan="2"><?= $modelProject->description; ?></td>
                                    </tr>
                                    <tr>
                                        <td><b>Date end</b></td>
                                        <td><?= $modelProject->end_date; ?></td>
                                        <td><b>Date create</b></td>
                                        <td><?= $modelProject->create_at; ?></td>
                                    </tr>
                                </table>
                            </div>
                            <?php foreach($arrayIdeas as $key => $ideas){ ?>
                                <h2><?= \Yii::$app->user->identity->getUsername($key); ?></h2>
                                <div class="col-sm-12" style="padding-left:100px;">
                                    <?php foreach($ideas as $idea){ ?>
                                        <div class="well">
                                            <?= $idea['ideas_description']; ?><br />
                                        </div>
                                    <?php } ?>
                                </div>
                                <div style="clear:both;"></div>
                            <?php } ?>     
                        </div>
                    </div>
                </div>
            </div>
            
       
          </div>
          <!-- Row End -->

          

        </div>

      </div>
    </div>
 